#!/bin/bash

cd bundle
for bundle in $(ls); do
	[ ! -d $bundle ] && continue
	[ ! -d $bundle/.git ] && continue
	# git managed plugin
	echo "Updating $bundle"
	(cd $bundle; git pull;)
	echo "$bundle updated"
done
echo "Building vimproc..."
(cd vimproc.vim && make) && echo "SUCCESS" || { echo "FAILED"; exit 1; }
