call setline(1, ['one', 'two', 'three'])
call planet#macros#Record('q')
call feedkeys("A!\<Esc>", 'xt')
call assert_equal('q', reg_recording())
call planet#macros#Stop()
call feedkeys('', 'xt')
call assert_equal('', reg_recording())
call assert_equal('one!', getline(1))
call cursor(2, 1)
call planet#macros#Play('q', 2)
call feedkeys('', 'xt')
call assert_equal('two!!', getline(2))
call setreg('a', "A?\<Esc>")
call cursor(2, 1)
xnoremap <F11> <Cmd>call planet#macros#Play('a', 1, 1, 0)<CR>
call feedkeys("Vj\<F11>", 'xt')
call assert_equal(['one!', 'two!!?', 'three?'], getline(1, 3))
xunmap <F11>
let s:popup = planet#macros#Preview('a')
call assert_true(s:popup > 0)
call popup_close(s:popup)
call assert_equal(0, planet#macros#Record(''))
call assert_equal(0, planet#macros#Play('a', 0))
call assert_equal(0, planet#macros#Stop())
