name: CI tests

on:
  pull_request:
    paths-ignore:
      - 'doc/*'
      - 'docker/*'
      - 'media/*'
      - '*.md'
  push:
    paths-ignore:
      - 'doc/*'
      - 'docker/*'
      - 'media/*'
      - '*.md'

env:
  SHELL: bash

jobs:
  run-tests:
    name: Test on ubuntu-latest
    runs-on: ubuntu-latest
    if: |
      ! startsWith(github.event.head_commit.message, 'doc:')
    steps:
    - name: Install packages
      run: |
        sudo add-apt-repository ppa:neovim-ppa/stable
        sudo apt update
        sudo apt install \
          vim neovim moreutils gcc \
          texlive texlive-latex-extra texlive-extra-utils \
          texlive-bibtex-extra libtext-bibtex-perl \
          texlive-publishers \
          latexmk \
          libmodule-build-perl \
          libconfig-autoconf-perl \
          libextutils-libbuilder-perl
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Test with neovim
      run: cd test && make -j1
    - name: Test with vim
      env:
        MYVIM: vim -T dumb --not-a-term -n
      run: cd test && make -j1
