vim9script

export def Update(): number
  if planet#menu#Visible('nav')
    # Buffers
    execute planet#menu_help#Entry('an 800.10  ', '📖&u.Buffers', '<Nop>')
    an disable 📖&u.Buffers
    execute planet#menu_help#Entry('an 800.10  ', '📖&u.C&hoose\.\.\.', ':Clap buffers<CR>')
    execute planet#menu_help#Entry('an 800.10  ', '📖&u.Manager\.\.\.', ':Bufexplorer<CR>')
    execute planet#menu_help#Entry('an 800.10  ', '📖&u.Open<Tab>:b', ':b<Space>')
    execute planet#menu_help#Entry('an 800.10  ', '📖&u.Open\ VSplit<Tab>:vert\ sb', ':vert sb<Space>')
    execute planet#menu_help#Entry('an 800.10  ', '📖&u.Open\ Tab<Tab>:tab\ sb', ':tab sb<Space>')
    execute planet#menu_help#Entry('an 800.10  ', '📖&u.Open\ All\ Loaded\ VSplit<Tab>:vert\ unh', ':vert unh<CR>')
    execute planet#menu_help#Entry('an 800.10  ', '📖&u.Open\ All\ Loaded\ Tab<Tab>:tab\ unh', ':tab unh<CR>')
    execute planet#menu_help#Entry('an 800.10  ', '📖&u.Open\ All\ VSplit<Tab>:vert\ ba', ':vert ba<CR>')
    execute planet#menu_help#Entry('an 800.10  ', '📖&u.Open\ All\ Tab<Tab>:tab\ ba', ':tab ba<CR>')
    execute planet#menu_help#Entry('an 800.20  ', '📖&u.--1--', '<Nop>')
    execute planet#menu_help#Entry('an 800.30  ', '📖&u.&Alternate<Tab>:b\ #<Tab><C-@>', '<C-^>')
    execute planet#menu_help#Entry('an 800.30  ', '📖&u.&Alternate\ Split<Tab>+^', '<C-w>^')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.--2--', '<Nop>')
    execute planet#menu_help#Entry('an 800.30  ', '📖&u.Next\ Modified<Tab>:bm', ':bm<CR>')
    execute planet#menu_help#Entry('an 800.30  ', '📖&u.Next\ Modified\ VSplit<Tab>:vert\ sbm', ':vert sbm<CR>')
    execute planet#menu_help#Entry('an 800.30  ', '📖&u.Next\ Modified\ Tab<Tab>:tab\ sbm', ':tab sbm<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.--3--', '<Nop>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.&First<Tab>[B', ':bf<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.&Previous<Tab>[b', ':bp<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.&Next<Tab>]b', ':bn<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.&Last<Tab>]B', ':bl<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.&First\ VSplit<Tab>:vert\ sbf', ':vert sbf<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.&Previous\ VSplit<Tab>:vert\ sbp', ':vert sbp<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.&Next\ VSplit<Tab>:vert\ sbn', ':vert sbn<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.&Last\ VSplit<Tab>:vert\ sbl', ':vert sbl<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.&First\ Tab<Tab>:tab\ sbf', ':tab sbf<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.&Previous\ Tab<Tab>:tab\ sbp', ':tab sbp<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.&Next\ Tab<Tab>:tab\ sbn', ':tab sbn<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.&Last\ Tab<Tab>:tab\ sbl', ':tab sbl<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.--4--', '<Nop>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.Add<Tab>:badd', ':badd<Space>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.Add\ as\ Alternate<Tab>:balt', ':balt<Space>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.Unload\ (Free\ Memory)', ':bun<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.Delete\ (Unload\ &&\ Unlist)', ':bd<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.Wipeout\ (Delete\ &&\ Clear\ Everything)', ':bw<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.--5--', '<Nop>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.Delete\ Hidden', ':call planet#buffer#DeleteHidden()<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.Delete\ All', ':call planet#buffer#DeleteAll()<CR>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.Execute\ in\ Each\ Buffer<Tab>:bufdo', ':bufdo<Space>')
    execute planet#menu_help#Entry('an 800.40  ', '📖&u.--6--', '<Nop>')

    # Arg List
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.Args', '<Nop>')
    an disable 🗃️&a.Args
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.Drop<Tab>:drop', ':drop %<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.&Add', ':argadd<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.&Delete', ':argdelete<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.&First<Tab>[A', ':first<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.&Previous<Tab>[a', ':previous<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.&Next<Tab>]a', ':next<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.&Last<Tab>]A', ':last<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.&First\ VSplit', ':vert sfirst<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.&Previous\ VSplit', ':vert sprevious<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.&Next\ VSplit', ':vert snext<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.&Last\ VSplit', ':vert slast<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.&First\ Tab', ':tab first<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.&Previous\ Tab', ':tab previous<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.&Next\ Tab', ':tab next<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.&Last\ Tab', ':tab last<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.All\ VSplit<Tab>:vert\ all', ':tabnew<CR>:vert all<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.All\ Tab<Tab>:tab\ all', ':tab all<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.--1--', '<Nop>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.Execute\ in\ Each\ Argument<Tab>:argdo', ':argdo<Space>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.--1--', '<Nop>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.Set\ Local', ':argl<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.Set\ Global', ':argg<CR>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.--2--', '<Nop>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.Run\ Each', ':argdo<Space>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.--3--', '<Nop>')
    execute planet#menu_help#Entry('an 810.10  ', '🗃️&a.Args\ List', '<Nop>')
    an disable 🗃️&a.Args\ List

    # Vim Windows
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.Windows', '<Nop>')
    an disable 🪟&w.Windows
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Window\ Mode', '<Cmd>WindowMode<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.ChooseWin\ Mode\ (&\\)<Tab>\\', '<Cmd>ChooseWin<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.--1--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.C&hoose<Tab>:Clap\ windows', '<Cmd>Clap windows<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.--2--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Vertical\ Split<Tab>:vsplit<Tab>+v', '<C-w>v')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.Horizontal\ &Split<Tab>:split<Tab>+s', '<C-w>s')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.VSplit\ &Bind', '<Cmd>call planet#window#SplitBind(''v'')<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&HSplit\ Bind', '<Cmd>call planet#window#SplitBind(''h'')<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.--3--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Move.&Swap<Tab>+x', '<C-w>x')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Move.Rotate\ &Up<Tab>R', '<C-w>R')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Move.Rotate\ &Down<Tab>r', '<C-w>r')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Move.To\ &Left<Tab>+H', '<C-w>H')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Move.To\ &Right<Tab>+L', '<C-w>L')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Move.To\ T&op<Tab>+K', '<C-w>K')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Move.To\ &Bottom<Tab>+J', '<C-w>J')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Move.To\ New\ &Tab<Tab>+T', '<C-w>T')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Move.To\ New\ &GUI\ Window', '<Cmd>call planet#gui#Transfer(v:true)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Move.&Copy\ To\ New\ Tab<Tab>+s+T', '<C-w>s<C-w>T')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Move.Copy\ To\ New\ &GUI\ Window', '<Cmd>call planet#gui#Transfer(v:false)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.--4--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Equal\ Size<Tab>+=', '<C-w>=')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.Ma&ximize<Tab>+_+\|', '<Cmd>call planet#window#Maximize()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Unmaximize<Tab>', '<Cmd>call planet#window#Restore()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Resize.Maximize\ &Vertically<Tab>+_', '<C-w>_')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Resize.Maximize\ &Horizontally<Tab>+\|', '<C-w>\|')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Resize.Increase\ Height<Tab>++', '<C-w>+')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Resize.Decrease\ Height<Tab>+-', '<C-w>-')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Resize.Increase\ Width<Tab>+>', '<C-w>>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Resize.Decrease\ Width<Tab>+<', '<C-w><')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.--6--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Focus.Alternate<Tab>+p', '<C-w>p')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Focus.Preview\ Window<Tab>+P', '<C-w>P')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Focus.Previous\ Window<Tab>+W', '<C-w>W')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Focus.Next\ Window<Tab>+w', '<C-w>w')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Focus.Top\ Window<Tab>+t', '<C-w>t')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Focus.Bottom\ Window<Tab>+b', '<C-w>b')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Focus.Left<Tab>+h', '<Cmd>call planet#window#Focus(''h'')<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Focus.Right<Tab>+l', '<Cmd>call planet#window#Focus(''l'')<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Focus.Up<Tab>+k', '<C-w>k')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Focus.Down<Tab>+j', '<C-w>j')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.--7--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.Set\ Fixed\ Size', '<Cmd>set winfixheight winfixwidth<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.--8--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Save', '<Cmd>call planet#windowview#Save()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Save\ 1', '<Cmd>call planet#windowview#Save(1)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Save\ 2', '<Cmd>call planet#windowview#Save(2)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Save\ 3', '<Cmd>call planet#windowview#Save(3)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Save\ 4', '<Cmd>call planet#windowview#Save(4)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Save\ 5', '<Cmd>call planet#windowview#Save(5)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Save\ 6', '<Cmd>call planet#windowview#Save(6)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Save\ 7', '<Cmd>call planet#windowview#Save(7)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Save\ 8', '<Cmd>call planet#windowview#Save(8)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Save\ 9\ (AutoSave)', '<Cmd>call planet#windowview#Save(9)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.--1--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Load', '<Cmd>call planet#windowview#Load()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Load\ 1', '<Cmd>call planet#windowview#Load(1)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Load\ 2', '<Cmd>call planet#windowview#Load(2)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Load\ 3', '<Cmd>call planet#windowview#Load(3)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Load\ 4', '<Cmd>call planet#windowview#Load(4)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Load\ 5', '<Cmd>call planet#windowview#Load(5)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Load\ 6', '<Cmd>call planet#windowview#Load(6)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Load\ 7', '<Cmd>call planet#windowview#Load(7)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Load\ 8', '<Cmd>call planet#windowview#Load(8)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Load\ 9\ (AutoSave)', '<Cmd>call planet#windowview#Load(9)<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.--2--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Toggle\ AutoSave\ Views', '<Cmd>call planet#windowview#ToggleAutoSave()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.--3--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.V&iew.Toggle\ Save\ Local\ Options', '<Cmd>call planet#windowview#ToggleLocalOptions()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Save', '<Cmd>let g:PV_layout = winrestcmd()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Save\ 1', '<Cmd>let g:PV_layout_1 = winrestcmd()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Save\ 2', '<Cmd>let g:PV_layout_2 = winrestcmd()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Save\ 3', '<Cmd>let g:PV_layout_3 = winrestcmd()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Save\ 4', '<Cmd>let g:PV_layout_4 = winrestcmd()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Save\ 5', '<Cmd>let g:PV_layout_5 = winrestcmd()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Save\ 6', '<Cmd>let g:PV_layout_6 = winrestcmd()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Save\ 7', '<Cmd>let g:PV_layout_7 = winrestcmd()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Save\ 8', '<Cmd>let g:PV_layout_8 = winrestcmd()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Save\ 9', '<Cmd>let g:PV_layout_9 = winrestcmd()<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.--1--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Load', '<Cmd>exe g:PV_layout<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Load\ 1', '<Cmd>exe g:PV_layout_1<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Load\ 2', '<Cmd>exe g:PV_layout_2<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Load\ 3', '<Cmd>exe g:PV_layout_3<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Load\ 4', '<Cmd>exe g:PV_layout_4<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Load\ 5', '<Cmd>exe g:PV_layout_5<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Load\ 6', '<Cmd>exe g:PV_layout_6<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Load\ 7', '<Cmd>exe g:PV_layout_7<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Load\ 8', '<Cmd>exe g:PV_layout_8<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.Load\ 9', '<Cmd>exe g:PV_layout_9<CR>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Layout.--1--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.--7--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.Execute\ in\ Window\ in\ This\ Tab', ':windo<Space>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.Execute\ in\ each\ Window', ':tabdo windo<Space>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.--5--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.--9--', '<Nop>')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.&Close<Tab>:close<Tab>+c', '<C-w>c')
    execute planet#menu_help#Entry('an 820.10  ', '🪟&w.Close\ &Other\ Windows<Tab>:only<Tab>+o', '<C-w>o')

    # Tabs
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.Tabs', '<Nop>')
    an disable 🗂️&t.Tabs
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.Tab\ Manager<Tab>:TMToggle', '<Cmd>TMToggle<CR>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.N&ew<Tab>:tabnew', '<Cmd>tabnew<CR>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.--1--', '<Nop>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.&Alternate<Tab>g\<Tab\>', 'g<Tab>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.C&hoose<Tab>:Clap\ windows', '<Cmd>Clap windows<CR>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.--2--', '<Nop>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.&First<Tab>:tabfirst', '<Cmd>tabfirst<CR>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.&Previous<Tab><C-PgUp><Tab>gT', 'gT')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.&Next<Tab><C-PgDown><Tab>gt', 'gt')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.&Last<Tab>:tablast', '<Cmd>tablast<CR>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.--3--', '<Nop>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.Move\ F&irst<Tab>:0tabmove', '<Cmd>0tabmove<CR>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.Move\ P&revious<Tab>:-tabmove', '<Cmd>-tabmove<CR>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.&Move\ Next<Tab>:+tabmove', '<Cmd>+tabmove<CR>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.Mo&ve\ Last<Tab>:tabmove', '<Cmd>tabmove<CR>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.--4--', '<Nop>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.&Save\ Current\ Tab', '<Cmd>call planet#tab#Save()<CR>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.Open\ &Tab\.\.\.', '<Cmd>call planet#tab#Open()<CR>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.--5--', '<Nop>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.E&xecute\ in\ each\ Tab<Tab>:tabdo', ':tabdo<Space>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.--6--', '<Nop>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.&Close<Tab>:tabclose', '<Cmd>call planet#tab#Close()<CR>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.Reopen\ Closed\ Tab', '<Cmd>call planet#tab#Reopen()<CR>')
    execute planet#menu_help#Entry('an 830.10  ', '🗂️&t.Close\ &Other\ Tabs<Tab>:tabonly', '<Cmd>call planet#tab#CloseOthers()<CR>')

    # Sessions
    execute planet#menu_help#Entry('an 840.10  ', '📚&s.Sessions', '<Nop>')
    an disable 📚&s.Sessions
    execute planet#menu_help#Entry('an 840.20  ', '📚&s.--1--', '<Nop>')
    execute planet#menu_help#Entry('an 840.30  ', '📚&s.&Save', '<Cmd>call planet#session#Save()<CR>')
    execute planet#menu_help#Entry('an 840.40  ', '📚&s.Save\ &As\.\.\.', '<Cmd>SSave<CR>')
    execute planet#menu_help#Entry('an 840.60  ', '📚&s.Ad&vanced\ Save.Save\ with\ Relative\ Paths', '<Cmd>call planet#session#SaveVariant(''relative'')<CR>')
    execute planet#menu_help#Entry('an 840.70  ', '📚&s.Ad&vanced\ Save.Save\ with\ Local\ Options', '<Cmd>call planet#session#SaveVariant(''local'')<CR>')
    execute planet#menu_help#Entry('an 840.80  ', '📚&s.Ad&vanced\ Save.Save\ with\ All\ Options', '<Cmd>call planet#session#SaveVariant(''all'')<CR>')
    execute planet#menu_help#Entry('an 840.90  ', '📚&s.Ad&vanced\ Save.Save\ without\ Global\ Vars', '<Cmd>call planet#session#SaveVariant(''no-globals'')<CR>')
    execute planet#menu_help#Entry('an 840.100 ', '📚&s.--2--', '<Nop>')
    execute planet#menu_help#Entry('an 840.100 ', '📚&s.Add\ &Menu\ Entry', '<Cmd>call planet#session#ManageDesktopFile(0, 0)<CR>')
    execute planet#menu_help#Entry('an 840.100 ', '📚&s.Add\ Des&ktop\ Entry', '<Cmd>call planet#session#ManageDesktopFile(0, 1)<CR>')
    execute planet#menu_help#Entry('an 840.100 ', '📚&s.--3--', '<Nop>')
    execute planet#menu_help#Entry('an 840.110 ', '📚&s.&Open', '<Cmd>call planet#session#Load('''')<CR>')
    execute planet#menu_help#Entry('an 840.120 ', '📚&s.Open\ &Last\ Session', '<Cmd>call planet#session#LoadLast()<CR>')
    execute planet#menu_help#Entry('an 840.130 ', '📚&s.&Reopen', '<Cmd>call planet#session#OpenPath(v:this_session)<CR>')
    execute planet#menu_help#Entry('an 840.140 ', '📚&s.--4--', '<Nop>')
    execute planet#menu_help#Entry('an 840.150 ', '📚&s.&Close', '<Cmd>SClose<CR>')
    execute planet#menu_help#Entry('an 840.160 ', '📚&s.--5--', '<Nop>')
    execute planet#menu_help#Entry('an 840.160 ', '📚&s.Remove\ Menu\ Entry', '<Cmd>call planet#session#ManageDesktopFile(1, 0)<CR>')
    execute planet#menu_help#Entry('an 840.160 ', '📚&s.Remove\ Desktop\ Entry', '<Cmd>call planet#session#ManageDesktopFile(1, 1)<CR>')
    execute planet#menu_help#Entry('an 840.160 ', '📚&s.--6--', '<Nop>')
    execute planet#menu_help#Entry('an 840.170 ', '📚&s.&Delete', '<Cmd>SDelete<CR>')

    # Vim Apps: Open in new GUI window
    execute planet#menu_help#Entry('an 850.10  ', '🗄️&x.GUI', '<Nop>')
    an disable 🗄️&x.GUI
    execute planet#menu_help#Entry('an 850.10  ', '🗄️&x.&Maximize', '<Cmd>call planet#gui#Window(''maximize'')<CR>')
    execute planet#menu_help#Entry('an 850.10  ', '🗄️&x.&Full\ Screen', '<Cmd>call planet#gui#Window(''fullscreen'')<CR>')
    execute planet#menu_help#Entry('an 850.10  ', '🗄️&x.Minimi&ze<Tab>:suspend<Tab><C-z>', '<C-z>')
    execute planet#menu_help#Entry('an 850.10  ', '🗄️&x.--1--', '<Nop>')
    execute planet#menu_help#Entry('an 850.10  ', '🗄️&x.&Start\ Vim\ Server', '<Cmd>call planet#gui#VimServerStart()<CR>')
    execute planet#menu_help#Entry('an 850.100 ', '🗄️&x.--2--', '<Nop>')

    # Control GUI window with wmctrl & vim servers
    execute planet#menu_help#Entry('an 860.10  ', '🎛️&@.Apps', '<Nop>')
    an disable 🎛️&@.Apps
    execute planet#menu_help#Entry('an 860.10  ', '🎛️&@.Calendar', '<Cmd>call planet#apps#Open(''Calendar'')<CR>')
    execute planet#menu_help#Entry('an 860.10  ', '🎛️&@.&Web\ Browser', '<Cmd>call planet#apps#Open(''W3m https://google.com/'', ''w3m'')<CR>')
    execute planet#menu_help#Entry('an 860.10  ', '🎛️&@.Calculator', '<Cmd>call planet#apps#Open(''Calculator'')<CR>')
    execute planet#menu_help#Entry('an 860.10  ', '🎛️&@.&Htop', '<Cmd>call planet#term#RunArgv([''htop''])<CR>')
    execute planet#menu_help#Entry('an 860.10  ', '🎛️&@.&Terminal', '<Cmd>call planet#apps#Open(''terminal ++curwin ++kill=kill'')<CR>')
    execute planet#menu_help#Entry('an 860.10  ', '🎛️&@.&File\ Manager', '<Cmd>call planet#apps#Open(''Fern .'')<CR>')
    execute planet#menu_help#Entry('an 860.10  ', '🎛️&@.&Python\ Notebook', '<Cmd>call planet#apps#Open(''Codi python'')<CR>')
    execute planet#menu_help#Entry('an 860.10  ', '🎛️&@.C&++\ Notebook', '<Cmd>call planet#apps#Open(''Codi cpp'')<CR>')
    execute planet#menu_help#Entry('an 860.300 ', '🎛️&@.--1--', '<Nop>')
    execute planet#menu_help#Entry('an 850.500 ', '🗄️&x.--2--', '<Nop>')
    execute planet#menu_help#Entry('an 860.600 ', '🎛️&@.Workspaces', '<Nop>')
    an disable 🎛️&@.Workspaces

    planet#view#Menus('nav')
    planet#search#Menus('nav')
  else
    silent! aunmenu 📖&u
    silent! aunmenu 🗃️&a
    silent! aunmenu 🪟&w
    silent! aunmenu 🗂️&t
    silent! aunmenu 📚&s
    silent! aunmenu 🗄️&x
    silent! aunmenu 🎛️&@
  endif
  return 0
enddef
