vim9script

export def Update(): number
  if planet#menu#Visible('settings')
    planet#display#Menus('settings')
    # Settings (Options) (unimpaired settings)
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.Settings', '<Nop>')
    an disable ⚙️&\\.Settings
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.Tabs:\ &2<Tab>:set\ et\ ts=2\ sw=2', ':set et ts=2 sw=2<CR>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.Tabs:\ &4<Tab>:set\ et\ ts=4\ sw=4', ':set et ts=4 sw=4<CR>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.Tabs:\ &8<Tab>:set\ noet\ ts=8\ sw=8', ':set noet ts=8 sw=8<CR>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.--1--', '<Nop>')
    execute planet#menu_help#Entry('am 970.10  ', '⚙️&\\.Toggle\ ''cursorline''<Tab>yoc', 'yoc')
    execute planet#menu_help#Entry('am 970.10  ', '⚙️&\\.Toggle\ ''hlsearch''<Tab>yoh', 'yoh')
    execute planet#menu_help#Entry('am 970.10  ', '⚙️&\\.Toggle\ ''ignorecase''<Tab>yoi', 'yoi')
    execute planet#menu_help#Entry('am 970.10  ', '⚙️&\\.Toggle\ ''number''<Tab>yon', 'yon')
    execute planet#menu_help#Entry('am 970.10  ', '⚙️&\\.Toggle\ ''relativenumber''<Tab>yor', 'yor')
    execute planet#menu_help#Entry('am 970.10  ', '⚙️&\\.Toggle\ ''cursorcolumn''<Tab>you', 'you')
    execute planet#menu_help#Entry('am 970.10  ', '⚙️&\\.Toggle\ ''virtualedit''<Tab>yov', 'yov')
    execute planet#menu_help#Entry('am 970.10  ', '⚙️&\\.Toggle\ ''wrap''<Tab>yow', 'yow')
    execute planet#menu_help#Entry('am 970.10  ', '⚙️&\\.Toggle\ word\ wrap', ':set lbr! lbr?<CR>')
    execute planet#menu_help#Entry('am 970.10  ', '⚙️&\\.Toggle\ ''cursorline''\ &&\ ''cursorcolumn''<Tab>yox', 'yox')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.--2--', '<Nop>')
    execute planet#menu_help#Entry('am 970.10  ', '⚙️&\\.''cmdheight'':\ 2', ':set cmdheight=2<CR>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.--3--', '<Nop>')
    execute planet#menu_help#Entry('am 970.10  ', '⚙️&\\.''scrolloff'':\ 0', ':set so=0<CR>')
    execute planet#menu_help#Entry('am 970.10  ', '⚙️&\\.''scrolloff'':\ 2\ (default)', ':set so=2<CR>')
    execute planet#menu_help#Entry('am 970.10  ', '⚙️&\\.''scrolloff'':\ 1000', ':set so=1000<CR>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.--4--', '<Nop>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.Set\ Text\ Width', ':call planet#settings#SetTextWidth()<CR>')
    execute planet#menu_help#Entry('an <silent> 970.10  ', '⚙️&\\.Set\ Line\ Endings\ (''fileformat'')', ':call planet#settings#SetLineEndings()<CR>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.--5--', '<Nop>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.Set\ ''path''', ':call planet#settings#SetPath()<CR>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.Set\ ''tags''', ':call planet#settings#SetTags()<CR>')
    for option in ['makeprg', 'grepprg', 'formatprg', 'equalprg', 'keywordprg', 'dictionary', 'thesaurus', 'include', 'define', 'suffixesadd']
      execute 'PlanetMenu an 970.10 ⚙️&\\.Buffer\ Options.' .. option
            \ .. ' <Cmd>call planet#settings#EditOption(' .. string(option) .. ')<CR>'
    endfor
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.--6--', '<Nop>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.Set\ GUI\ Dialogs', ':call planet#planet#SetGuiDialogs()<CR>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.Set\ Text\ Dialogs', ':call planet#planet#SetTextDialogs()<CR>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.--7--', '<Nop>')
    if has("win32") || has("gui_gtk")
      execute planet#menu_help#Entry('an 970.10 ', '⚙️&\\.Select\ Fo&nt\.\.\.', ':set guifont=*<CR>')
    endif
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.--8--', '<Nop>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.Set\ Window-Local\ Syntax<Tab>:ownsyntax\ {syn}', 'q:iownsyntax <C-x><C-v>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.--9--', '<Nop>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.Toggle\ Verbosity<Tab>=oV', ':VerbosityToggle<CR>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.Open\ Verbosity\ Log<Tab>goV', ':VerbosityOpenLast<CR>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.--10--', '<Nop>')
    execute planet#menu_help#Entry('an 970.10  ', '⚙️&\\.Settings\ Buffer<Tab>:options', ':options<CR>')

    # Show current maps (nnoremap, etc.)
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Maps', '<Nop>')
    an disable ⌨️&\|.Maps
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.C&hoose\.\.\.', ':Clap maps<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Information', '<Nop>')
    an disable ⌨️&\|.Information
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Cursor\ Filename<Tab><C-g>', '<C-g>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Cursor\ Position<Tab>g<C-g>', 'g<C-g>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Character\ under\ Cursor<Tab>g8', 'g8')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Ascii\ under\ Cursor<Tab>ga', 'ga')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Output\ of\ previous\ Command<Tab>g<', 'g<')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.List\ All\ QF', ':clist!<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.List\ All\ LL', ':llist!<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.List\ QF\ Lists', ':chistory<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.List\ LL\ Lists', ':lhistory<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Current\ Colorscheme', ':colorscheme<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Clear\ Buffer\ Syntax<Tab>:syn\ clear', ':syn clear<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.On\ (Reset\ Highlight)<Tab>:syn\ on', ':syn on<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Enable\ (Keep\ Highlight)<Tab>:syn\ enable', ':syn enable<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Toggle', ':if exists("g:syntax_on") \| syntax off \| else \| syntax enable \| endif<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Default<Tab>:syn\ default', ':syn default<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Manual<Tab>:syn\ manual', ':syn manual<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Off<Tab>:syn\ off', ':syn off<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Reset<Tab>:syn\ reset', ':syn reset<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.List<Tab>:syn\ list', ':syn list<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Case<Tab>:syn\ case', ':syn case<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Foldlevel<Tab>:syn\ foldlevel', ':syn foldlevel<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Spell<Tab>:syn\ spell', ':syn spell<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.iskeyword<Tab>:syn\ iskeyword', ':syn iskeyword<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.conceal<Tab>:syn\ conceal', ':syn conceal<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Sync\ List<Tab>:syn\ sync', ':syn sync<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Sync\ FromStart<Tab>:syn\ sync\ fromstart', ':syn sync fromstart<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Sync\ Ccomment<Tab>:syn\ sync\ ccomment', ':syn sync ccomment<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Sync\ Minlines<Tab>:syn\ sync\ minlines=50', ':syn sync minlines=50<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Sync\ Clear<Tab>:syn\ sync\ clear', ':syn sync clear<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Highlight\ List<Tab>:hi', ':hi<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Syntax.Highlight\ Clear<Tab>:hi\ clear', ':hi clear<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Co&lor\ Test', ':sp $VIMRUNTIME/syntax/colortest.vim<Bar>so %<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.&Highlight\ Test', ':runtime syntax/hitest.vim<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.&Spell\ Dump<Tab>:spelldump', ':spelldump<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Run\ Vim\ Script', ':browse so<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Source\ Current\ Vim\ Script', ':so %<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Ex\ Vim\ Mode\ (Dangerous!)<Tab>gX', 'gQ')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Ex\ Mode\ (Dangerous!)<Tab>Q', 'Q')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Open\ $VIMRUNTIME\ Folder', ':tabnew<CR>:Fern $VIMRUNTIME<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Debug', '<Nop>')
    an disable ⌨️&\|.Debug
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Profile\ Syntax.Start\ measuring\ syntax\ times<Tab>:syntime\ on', ':syntime on<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Profile\ Syntax.Stop\ measuring\ syntax\ times<Tab>:syntime\ off', ':syntime off<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Profile\ Syntax.Restart\ measuring\ syntax\ times<Tab>:syntime\ clear', ':syntime clear<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.Profile\ Syntax.Report\ syntax\ times<Tab>:syntime\ report', ':syntime report<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.WinBar.Set\ for\ QF/LL', '<Cmd>call planet#winbar#Preset(''quickfix'')<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.WinBar.Set\ for\ Terminal', '<Cmd>call planet#winbar#Preset(''terminal'')<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.WinBar.Set\ for\ Output', '<Cmd>call planet#winbar#Preset(''terminal'')<CR>')
    execute planet#menu_help#Entry('an 980.10  ', '⌨️&\|.WinBar.Clear', '<Cmd>call planet#winbar#Change(''clear'')<CR>')

    # Help
    execute planet#menu_help#Entry('an 990.10  ', '❔&?.Help', '<Nop>')
    an disable ❔&?.Help
    execute planet#menu_help#Entry('an 990.10  ', '❔&?.Help\ Contents', '<Cmd>h<CR>')
    execute planet#menu_help#Entry('an 990.10  ', '❔&?.&Lookup\ Word\ under\ Cursor<Tab>K', 'K')
    execute planet#menu_help#Entry('an 990.10  ', '❔&?.&TLDR\ Word\ under\ Cursor', '<Cmd>call planet#term#RunArgv([''tldr'', expand(''<cword>'')])<CR>')
    execute planet#menu_help#Entry('an 990.20  ', '❔&?.Inde&x', '<Cmd>h index<CR>')
    execute planet#menu_help#Entry('an 990.30  ', '❔&?.&QuickRef', '<Cmd>h quickref<CR>')
    execute planet#menu_help#Entry('an 990.40  ', '❔&?.&Plugins\ Documentation', '<Cmd>h local-additions<CR>')
    execute planet#menu_help#Entry('an 990.50  ', '❔&?.View\ Log\ Messages<Tab>:messages', '<Cmd>messages<CR>')
    execute planet#menu_help#Entry('an 990.60  ', '❔&?.--1--', '<Nop>')
    execute planet#menu_help#Entry('an 990.70  ', '❔&?.View\ &PlanetVim\ Community', '<Cmd>call planet#gui#OpenUrl(''https://matrix.to/#/+planetvim:matrix.org'')<CR>')
    execute planet#menu_help#Entry('an 990.70  ', '❔&?.&Join\ PlanetVim\ Chat', '<Cmd>call planet#gui#OpenUrl(''https://matrix.to/#/#planetvim_discussion:matrix.org?via=matrix.org'')<CR>')
    execute planet#menu_help#Entry('an 990.80  ', '❔&?.--2--', '<Nop>')
    execute planet#menu_help#Entry('an 990.90  ', '❔&?.Check\ for\ &Updates', '<Cmd>call planet#gui#OpenUrl(''https://github.com/fedorenchik/PlanetVim/releases'')<CR>')
    execute planet#menu_help#Entry('an 990.100 ', '❔&?.Add\ Feature\ Request', '<Cmd>call planet#gui#OpenUrl(''https://github.com/fedorenchik/PlanetVim/issues/new?labels=enhancement&template=feature_request.md'')<CR>')
    execute planet#menu_help#Entry('an 990.100 ', '❔&?.Report\ PlanetVim\ &Issue', '<Cmd>call planet#gui#OpenUrl(''https://github.com/fedorenchik/PlanetVim/issues/new?template=bug_report.md'')<CR>')
    execute planet#menu_help#Entry('an 990.110 ', '❔&?.--3--', '<Nop>')
    execute planet#menu_help#Entry('an 990.110 ', '❔&?.Others.Emergency\ Exit', '<Cmd>call planet#planet#EmergencyExit()<CR>')
    execute planet#menu_help#Entry('an 990.110 ', '❔&?.Others.Restore\ PlanetVim\ Menu', '<Cmd>call planet#planet#PlanetToggle()<CR>')
    execute planet#menu_help#Entry('an 990.110 ', '❔&?.--4--', '<Nop>')
    execute planet#menu_help#Entry('an 990.110 ', '❔&?.&Close\ Help\ Window', '<Cmd>helpclose<CR>')
    execute planet#menu_help#Entry('an 990.110 ', '❔&?.--5--', '<Nop>')
    execute planet#menu_help#Entry('an 990.120 ', '❔&?.&About', '<Cmd>version<CR>')
    planet#completion#Menus('settings')
    planet#buffer_options#Menus('settings')
    planet#input#Menus('settings')
    planet#appearance#Menus()
    planet#learn#Menus()
  else
    silent! aunmenu ⚙️&\\
    silent! aunmenu ⌨️&\|
    silent! aunmenu ❔&?
  endif
  return 0
enddef
