name: "test status"
on:
  - "push"
jobs:
  test:
    runs-on: "ubuntu-18.04"
    strategy:
      matrix:
        include:
          - vim_type: "Vim"
            vim_version: "v8.2.2277"
            vspec_vim: "vim"
          - vim_type: "Neovim"
            vim_version: "stable"
            vspec_vim: "nvim"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 5
      - name: "install ${{ matrix.vim_type }}"
        uses: "thinca/action-setup-vim@v1"
        with:
          vim_version: "${{ matrix.vim_version }}"
          vim_type: "${{ matrix.vim_type }}"
      - name: "install ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: "run tests"
        run: |
          ${{ matrix.vspec_vim }} --version
          script -qec " VSPEC_VIM=${{ matrix.vspec_vim }} rake test"
  lint:
    runs-on: "ubuntu-18.04"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: "run vint"
        # Must remove syntax before linting
        # https://github.com/vim-jp/vim-vimlparser/issues/98
        # Must remove tests before linting
        # https://github.com/Vimjas/vint/issues/330
        run: |
          sudo python3 -m pip install vim-vint
          sed -i 's/^syntax .*//' syntax/floggraph.vim
          rm -rf t/
          vint --color .
