cmake_minimum_required(VERSION 3.16)
project(planet_form LANGUAGES CXX)
set(CMAKE_AUTOUIC ON)
find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Widgets)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Widgets)
add_executable(planet_form main.cpp MainWindow.hpp mainwindow.ui)
target_link_libraries(planet_form PRIVATE Qt${QT_VERSION_MAJOR}::Widgets)
